### ISSUE TITLE
thread locals ought to not be used in allocators

### ISSUE THREAD

**Issue by nagisa** [Protryon/alloc-track#1]
I came here from the reddit on this crate.

A common issue with crates attempting an implementation like this, including this crate itself, is use of thread locals. In particular I’ve seen something about THREAD_IDs in the implementation of this crate. They may not be used in the implementation of an allocator, for two reasons:

1. The allocator might be required to set up thread locals in the first place, which then would lead to reentrancy where one isn’t expected. This is usually going to result in a panic of some sort.
2. Setting up a thread may attempt to allocate before the thread locals are initialized for the thread.

This is all dependent on the implementation of the thread locals, of course. But none of the implementation details are guaranteed by libstd as far as I am aware and therefore this crate may break as the implementation of libstd is changed (or varies between targets). Though admittedly a case may be made that something like that would be a breaking change…

**Comment by Protryon** [comment]
We have a re-entrancy failsafe to avoid any cyclical calls.

As for thread locals issues, I haven't seen any in the wild and this is a diagnostic tool, not something to deploy into production long term.

I personally have only deployed this in production for short periods at most.
